//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHang
    {
        public string MaKieu { get; set; }
        public string MaCuaHang { get; set; }
        public int SoLuong { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
        public virtual ChiTietSP ChiTietSP { get; set; }
    }
}
