//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietSPs = new HashSet<ChiTietSP>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string CPU { get; set; }
        public string Ram { get; set; }
        public string BoNhoTrong { get; set; }
        public string BoNhoNgoai { get; set; }
        public string Sim { get; set; }
        public string ManHinh { get; set; }
        public string DungLuongPin { get; set; }
        public string Camera { get; set; }
        public string CardManHinh { get; set; }
        public string OS { get; set; }
        public string Port { get; set; }
        public string TrongLuong { get; set; }
        public string ThongTinKhac { get; set; }
        public string MaDSP { get; set; }
        public string NămSX { get; set; }
    
        public virtual DongSanPham DongSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSP> ChiTietSPs { get; set; }
    }
}
