//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string MaCuaHang { get; set; }
        public string MaLoaiTK { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
